set nocompatible
set termguicolors
set encoding=utf-8
set nowrap
set ruler
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set incsearch
set nohlsearch
set autoindent
set ignorecase
set smartcase
set wildmenu 
set noswapfile 
set nowritebackup
set nobackup
set backspace=indent,eol,start
set path+=**
set hidden
set omnifunc=syntaxcomplete#Complete
set pumheight=10 
set clipboard=unnamed
syntax on
filetype plugin indent on
colorscheme torte
